services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: shahnawaz52
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kubecortex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shahnawaz52 -d kubecortex"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL: postgresql+psycopg://shahnawaz52:admin@postgres:5432/kubecortex
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    command: python -m app.worker
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL: postgresql+psycopg://shahnawaz52:admin@postgres:5432/kubecortex
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  dashboard:
    build: ./dashboard
    ports:
      - "5173:5173"
    volumes:
      - ./dashboard/src:/app/src
    depends_on:
      - api

volumes:
  pgdata:
